New content for dry-run install
ondat/documentation pull request #25
Opened 2022-02-03 20:52 UTC by mdeneva

Added some new content to the kubectl page. Please review and suggest whether we need more or something I say is not technically correct, thanks :)

2022-02-08 11:44 UTC, cvlc commented on docs/reference/kubectl-plugin.md
> +* Create a YAML to describe the cluster's resources using a [Heml chart](https://github.com/storageos/charts/pull/129) or use the kubectl plugin with the dry-run flags enabled:
Heml -> Helm

2022-02-08 11:44 UTC, cvlc commented on docs/reference/kubectl-plugin.md
> +`kubecl storageos install --username c3RvcmFnZW9z --password c3RvcmFnZW9z --include-etcd ... --dry-run`
kubecl -> kubectl

2022-02-10 14:00 UTC, Arau reviewed
I'm happy to approve following the changes that @cvlc mentioned about the cosmetic typos. Happy to merge when those are fixed 😄

2022-02-10 14:00 UTC, Arau commented on docs/reference/kubectl-plugin.md
>      kubectl storageos install --stos-cluster-yaml StorageOSCluster.yaml --etcd-endpoints "storageos-etcd-client.storageos-etcd:2379"
This is not part of the change, but we are here, so I'd compact the shell lines for readability

```
kubectl storageos install \
    --stos-cluster-yaml StorageOSCluster.yaml \
    --etcd-endpoints "storageos-etcd-client.storageos-etcd:2379"
```

2022-02-15 17:53 UTC, cvlc requested changes

2022-02-15 17:53 UTC, cvlc commented
Oops, just noticed a small issue! `c3RvcmFnZW9z` is the base64-encoded string `storageos` but it won't be unencoded by the operator, so we should pass that value in as plaintext!

2022-02-22 10:10 UTC, Arau commented
Changed base to [release/v2.6.0](https://github.com/ondat/documentation/tree/release/v2.6.0) branch rather than merge.

2022-02-23 14:51 UTC, Arau commented on docs/reference/kubectl-plugin.md
> +  > Note, that when `--dry-run` is set for an install command, no installation takes place. Instead, the installation manifests that would have been installed under normal > circumstances are written
there is a > in the middle of the line

2022-02-23 20:49 UTC, cvlc approved these changes

2022-02-24 10:10 UTC, merged