New content
ondat/documentation pull request #27
Opened 2022-02-07 14:27 UTC by mdeneva

2022-02-08 11:42 UTC, cvlc commented on docs/reference/cluster-operator/examples.md
> +resources:
Missing a `name:` here

2022-02-08 11:42 UTC, cvlc commented on docs/reference/cluster-operator/examples.md
>  we do not currently recommend applying upper limits to resources for Ondat
Maybe we should remove this, as it conflicts with the following content that provides limits.

2022-02-10 13:55 UTC, Arau requested changes
Thank you for the change. 

I believe @DavidMarchant made changes on the api-manager requests and limits, it is worth doublechecking that we set the latest ones.

2022-02-10 13:55 UTC, Arau commented on docs/reference/cluster-operator/examples.md
> +name: provisioner
the indentation broke for the `name` fields.

2022-02-22 10:11 UTC, Arau approved these changes
Good to merge in my opinion. 

It would be great to merge before release 2.6 so we can incorporate in both 2.5 and latest for the next release.

2022-02-25 17:28 UTC, cannischan commented
@Arau did we merge this at the end for 2.6.0 release branch?

2022-02-25 17:31 UTC, cannischan commented
Hi @mdeneva , please fix the lint error and prepare this PR to be merged - this should go out together with 2.6.0 due to the operator limit that was added.

2022-02-28 14:51 UTC, cvlc approved these changes

2022-02-28 15:22 UTC, merged