[2.7.0] Add Release notes and update 2.6.0 references
ondat/documentation pull request #98
Opened 2022-03-30 17:49 UTC by cannischan

- Adds release notes of 2.7.0
- Update reference from 2.6.0 o 2.7.0

Please review if the release notes and the update to the version numbers make sense

2022-03-30 18:29 UTC, mhmxs approved these changes
Thanks

2022-03-31 08:57 UTC, DavidMarchant approved these changes

2022-03-31 15:28 UTC, hubvu commented
+1 from me!

2022-03-31 15:29 UTC, hubvu approved these changes

2022-03-31 17:51 UTC, DavidMarchant requested changes
This looks good but I've added a few comments for changes to the release notes

I think more generally this is a departure from the format of the rest of the release notes which have been more general, particularly with bug fixes, & I just want to make sure that it's a conscious departure

2022-03-31 17:51 UTC, DavidMarchant commented on docs/release-notes.md
> +- Fixed a bug where the Ondat Operator v2.7.0 does not work with OpenShift 4.7
I don't think this should be here - it's not a change as the issue didn't exist in any released version of the product.

2022-03-31 17:51 UTC, DavidMarchant commented on docs/release-notes.md
> +- Rewrote the RPC interface between the Control Plane and the Data Plane. All of the old `ctl` tools have been removed and we have added a single `supctl` tool that can be used to debug/program the D
Please don't mention the supctl tool's existence, we explicitly don't want customers touching it without our hands on help.

2022-03-31 17:51 UTC, DavidMarchant commented on docs/release-notes.md
> +- Skipped duplicated nodes by hostname during sync
Just speaking personally, I don't know what this means so I wouldn't expect customers to know either

2022-03-31 17:51 UTC, DavidMarchant commented on docs/release-notes.md
> +- Fixed an issue that caused replicas to go into the “unknown” state during failover
The word 'rarely' should probably feature in this sentence somewhere :smile: I think we're selling ourselves a bit short to new eyes here, likewise with the line above

2022-04-04 15:51 UTC, cannischan commented
@DavidMarchant please review - made changes with your comments

2022-04-05 13:24 UTC, DavidMarchant approved these changes
Thanks @cannischan! lgtm

2022-04-05 13:31 UTC, merged